### ISSUE TITLE
Hi, I just want to ask you about the send notification to Android issue that you raised in the GitHub

### ISSUE THREAD

**Issue by tananes** [iarmankhan/iarmankhan#1]
Hi Khan,  
My name is Bird, nice to meet you, I'm struggling to the same problem as you raised here:
https://github.com/zo0r/react-native-push-notification/issues/1471

I just want to ask you if you can solve it yet or not?

What happens to me is :
1. I run my app from Android, then I press a Home button to make it running the app in a background process
2. I update some values from the backend, it should send a notification
3. In the app side, if I open the the app, the notification will send to the right channel-id which is good,  but if I'm not opening my app (running it as a background process) it will send me to the **miscellaneous** channel (It's created by automatically, I don't want it)

What I expect is :
When I run my app as a background process. the notification should send to the right custom channel (depend on channel-ID), it should work as same as when I open the app

It would be my pleasure if I receive some suggestion from you
Sorry if this message disturb you

Thank you

**Comment by iarmankhan** [comment]
Hey @tananes I actually moved to https://notifee.app/ as this pretty much solve all my use cases. Hope this helps. Thanks
